In [1]:
import pandas as pd
import numpy as np
import sklearn as sk

from datascience import *

import matplotlib
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

In [12]:
energy = pd.read_csv('energy_clean.csv',index_col=0)

energy = energy.drop(energy.columns[np.array([0,3,4,5,6,7,8,9,10])], axis=1)

energy['resi'] = energy['Berkeley'] + energy['Hopper']

energy['resi'] = energy['resi']/energy['resi'].max()

energy = energy.drop(energy.columns[np.array([0,1])], axis=1)

energy

                         resi
2018-01-01 01:00:00  0.516765
2018-01-01 02:00:00  0.438856
2018-01-01 03:00:00  0.470743
2018-01-01 04:00:00  0.467127
2018-01-01 05:00:00  0.466798
2018-01-01 06:00:00  0.473702
2018-01-01 07:00:00  0.465812
2018-01-01 08:00:00  0.492439
2018-01-01 09:00:00  0.523340
2018-01-01 10:00:00  0.513807
2018-01-01 11:00:00  0.511177
2018-01-01 12:00:00  0.522682
2018-01-01 13:00:00  0.514135
2018-01-01 14:00:00  0.516108
2018-01-01 15:00:00  0.514464
2018-01-01 16:00:00  0.506246
2018-01-01 17:00:00  0.511177
2018-01-01 18:00:00  0.528271
2018-01-01 19:00:00  0.518738
2018-01-01 20:00:00  0.498356
2018-01-01 21:00:00  0.501315
2018-01-01 22:00:00  0.485536
2018-01-01 23:00:00  0.471072
2018-01-02 00:00:00  0.475016
2018-01-02 01:00:00  0.503287
2018-01-02 02:00:00  0.425378
2018-01-02 03:00:00  0.475016
2018-01-02 04:00:00  0.464497
2018-01-02 05:00:00  0.463840
2018-01-02 06:00:00  0.462853
...                       ...
2018-07-26 18:00:00  0.568705
2018-07-26 19:00:00  0.612097
2018-07-26 20:00:00  0.565417
2018-07-26 21:00:00  0.621959
2018-07-26 22:00:00  0.475674
2018-07-26 23:00:00  0.478304
2018-07-27 00:00:00  0.386259
2018-07-27 01:00:00  0.453320
2018-07-27 02:00:00  0.373767
2018-07-27 03:00:00  0.456279
2018-07-27 04:00:00  0.365878
2018-07-27 05:00:00  0.432281
2018-07-27 06:00:00  0.360618
2018-07-27 07:00:00  0.523669
2018-07-27 08:00:00  0.542735
2018-07-27 09:00:00  0.673570
2018-07-27 10:00:00  0.621631
2018-07-27 11:00:00  0.703156
2018-07-27 12:00:00  0.636752
2018-07-27 13:00:00  0.660750
2018-07-27 14:00:00  0.641026
2018-07-27 15:00:00  0.674885
2018-07-27 16:00:00  0.667982
2018-07-27 17:00:00  0.596647
2018-07-27 18:00:00  0.598948
2018-07-27 19:00:00  0.567061
2018-07-27 20:00:00  0.601907
2018-07-27 21:00:00  0.529915
2018-07-27 22:00:00  0.511834
2018-07-27 23:00:00  0.433925

[4990 rows x 1 columns]